//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.MPTimer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000-01-01")]
        public global::System.DateTime LastUpdateDatetime {
            get {
                return ((global::System.DateTime)(this["LastUpdateDatetime"]));
            }
            set {
                this["LastUpdateDatetime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color ProgressBarColor {
            get {
                return ((global::System.Drawing.Color)(this["ProgressBarColor"]));
            }
            set {
                this["ProgressBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メイリオ, 9.75pt")]
        public global::System.Drawing.Font Font {
            get {
                return ((global::System.Drawing.Font)(this["Font"]));
            }
            set {
                this["Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int OverlayLeft {
            get {
                return ((int)(this["OverlayLeft"]));
            }
            set {
                this["OverlayLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int OverlayTop {
            get {
                return ((int)(this["OverlayTop"]));
            }
            set {
                this["OverlayTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGoldenrodYellow")]
        public global::System.Drawing.Color FontColor {
            get {
                return ((global::System.Drawing.Color)(this["FontColor"]));
            }
            set {
                this["FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int OverlayOpacity {
            get {
                return ((int)(this["OverlayOpacity"]));
            }
            set {
                this["OverlayOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CountInCombat {
            get {
                return ((bool)(this["CountInCombat"]));
            }
            set {
                this["CountInCombat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int TargetJobId {
            get {
                return ((int)(this["TargetJobId"]));
            }
            set {
                this["TargetJobId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int CountInCombatSpan {
            get {
                return ((int)(this["CountInCombatSpan"]));
            }
            set {
                this["CountInCombatSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClickThrough {
            get {
                return ((bool)(this["ClickThrough"]));
            }
            set {
                this["ClickThrough"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color ProgressBarOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["ProgressBarOutlineColor"]));
            }
            set {
                this["ProgressBarOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGoldenrodYellow")]
        public global::System.Drawing.Color FontOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["FontOutlineColor"]));
            }
            set {
                this["FontOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110, 7")]
        public global::System.Drawing.Size ProgressBarSize {
            get {
                return ((global::System.Drawing.Size)(this["ProgressBarSize"]));
            }
            set {
                this["ProgressBarSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int ParameterRefreshRate {
            get {
                return ((int)(this["ParameterRefreshRate"]));
            }
            set {
                this["ParameterRefreshRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double MPRecoveryInterval {
            get {
                return ((double)(this["MPRecoveryInterval"]));
            }
            set {
                this["MPRecoveryInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color ProgressBarShiftColor {
            get {
                return ((global::System.Drawing.Color)(this["ProgressBarShiftColor"]));
            }
            set {
                this["ProgressBarShiftColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color ProgressBarOutlineShiftColor {
            get {
                return ((global::System.Drawing.Color)(this["ProgressBarOutlineShiftColor"]));
            }
            set {
                this["ProgressBarOutlineShiftColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ProgressBarShiftTime {
            get {
                return ((double)(this["ProgressBarShiftTime"]));
            }
            set {
                this["ProgressBarShiftTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color EnochianProgressBarColor {
            get {
                return ((global::System.Drawing.Color)(this["EnochianProgressBarColor"]));
            }
            set {
                this["EnochianProgressBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メイリオ, 9.75pt")]
        public global::System.Drawing.Font EnochianFont {
            get {
                return ((global::System.Drawing.Font)(this["EnochianFont"]));
            }
            set {
                this["EnochianFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int EnochianOverlayLeft {
            get {
                return ((int)(this["EnochianOverlayLeft"]));
            }
            set {
                this["EnochianOverlayLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int EnochianOverlayTop {
            get {
                return ((int)(this["EnochianOverlayTop"]));
            }
            set {
                this["EnochianOverlayTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGoldenrodYellow")]
        public global::System.Drawing.Color EnochianFontColor {
            get {
                return ((global::System.Drawing.Color)(this["EnochianFontColor"]));
            }
            set {
                this["EnochianFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGoldenrodYellow")]
        public global::System.Drawing.Color EnochianFontOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["EnochianFontOutlineColor"]));
            }
            set {
                this["EnochianFontOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color EnochianProgressBarOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["EnochianProgressBarOutlineColor"]));
            }
            set {
                this["EnochianProgressBarOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110, 7")]
        public global::System.Drawing.Size EnochianProgressBarSize {
            get {
                return ((global::System.Drawing.Size)(this["EnochianProgressBarSize"]));
            }
            set {
                this["EnochianProgressBarSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color EnochianProgressBarShiftColor {
            get {
                return ((global::System.Drawing.Color)(this["EnochianProgressBarShiftColor"]));
            }
            set {
                this["EnochianProgressBarShiftColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OrangeRed")]
        public global::System.Drawing.Color EnochianProgressBarOutlineShiftColor {
            get {
                return ((global::System.Drawing.Color)(this["EnochianProgressBarOutlineShiftColor"]));
            }
            set {
                this["EnochianProgressBarOutlineShiftColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double EnochianProgressBarShiftTime {
            get {
                return ((double)(this["EnochianProgressBarShiftTime"]));
            }
            set {
                this["EnochianProgressBarShiftTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enochian")]
        public string EnochianLabel {
            get {
                return ((string)(this["EnochianLabel"]));
            }
            set {
                this["EnochianLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnabledMPTimer {
            get {
                return ((bool)(this["EnabledMPTimer"]));
            }
            set {
                this["EnabledMPTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnabledEnochianTimer {
            get {
                return ((bool)(this["EnabledEnochianTimer"]));
            }
            set {
                this["EnabledEnochianTimer"] = value;
            }
        }
    }
}
